### PR TITLE
refinement & makeRefinement

### PR DESCRIPTION
**Pull request by anthonyjoeseph**
Closes https://github.com/pfgray/ts-adt/issues/19

### CODE REVIEW

**Comment by anthonyjoeseph** [comment]
@pfgray would you be more comfortable if I used your original implementation? https://github.com/pfgray/ts-adt/issues/19#issuecomment-835833128

**Comment by pfgray** [comment]
Nah, this looks perfect, apologies for the delay

**Comment by pfgray** [comment]
I tweaked it a bit to take a variable amount of tags, should be available in v2.1.0 now, thanks!

**Comment by anthonyjoeseph** [comment]
Amazing, thank you!

**Pull request merged**
